extends RefCounted
# Dual-grid water/land coast transition tile set (Phase 2 step 3, D1/D2 of
# docs/superpowers/specs/2026-09-12-pixel-world-at-scale-design.md).
#
# The autotile grid is offset half a cell from the terrain id grid: each
# 16x16 tile here sits at a shared corner of 4 terrain cells and is picked by
# a 4-bit mask of which of those cells is water. Bit order (matches
# autotile.gdshaderinc):
#
#   bit 0 (1)  = top-left  (TL) cell is water
#   bit 1 (2)  = top-right (TR) cell is water
#   bit 2 (4)  = bottom-left  (BL) cell is water
#   bit 3 (8)  = bottom-right (BR) cell is water
#
# Masks 0 (all land) and 15 (all water) need no overlay — the flat land/water
# shader branches already look right — so their tiles are fully transparent.
# The other 14 masks fall into 4 shape families under 90-degree rotation:
#
#   CORNER   (1 bit set,  4 masks: 1, 2, 8, 4)   — a small water wedge biting
#             into one corner of an otherwise-land tile.
#   EDGE     (2 adjacent bits, 4 masks: 3, 10, 12, 5) — a straight coastline,
#             water on one half of the tile.
#   DIAGONAL (2 opposite bits, 2 masks: 9, 6)    — a checkerboard corner pair,
#             water wedges in two opposite corners.
#   INNER    (3 bits set, 4 masks: 14, 13, 7, 11) — the complement of CORNER:
#             a small land wedge (with its own beach) surrounded by water.
#             This is the same shape family the design doc also calls
#             "three-water" or "inner corner" — one base shape, water and
#             land swapped relative to CORNER.
#
# Only ONE base pixel map per family is hand-authored below; the other 3
# orientations in each family are generated by rotating the base 90 degrees
# at a time (`_rotate_rows_cw`), with `rotate_mask_cw` performing the matching
# bit permutation so art and mask always agree. This is the same "square
# atlas, everything generated from a small authored set" discipline
# terrain_sprites.gd uses for its mirrored variant 2.

const CELL_PX := 16
const ATLAS_COLS := 4  # 4x4 square atlas (Metal constraint): 16 cells = 16 masks.

# --- palette -----------------------------------------------------------
# 'a' dry sand, 'b' wet sand, 'c' shallow water, 'f' foam. '.' (unused in the
# base maps below, kept for parity with terrain_sprites' `_sprite` helper)
# is transparent.
const _PALETTE := {
	"a": "d9c58a",
	"b": "bfa86e",
	"c": "2f6f9c",
	"f": "bcd8e6",
}

# --- base shapes (one per family, mask 0 rotations) ---------------------
# Generated from simple corner-distance bands so every pixel nearest a water
# corner lands exactly on 'c' and every pixel nearest a land corner lands
# exactly on 'a' (see test_coast_tiles.gd's corner-colour property) — see
# scripts/gen_coast.py-style derivation in the PR description for the exact
# thresholds; reproduced here as plain data.

# CORNER base = mask 1 (TL water only): a diagonal wedge from the TL corner.
const _BASE_CORNER: PackedStringArray = [
	"cccccccfffbbbaaa",
	"ccccccfffbbbaaaa",
	"cccccfffbbbaaaaa",
	"ccccfffbbbaaaaaa",
	"cccfffbbbaaaaaaa",
	"ccfffbbbaaaaaaaa",
	"cfffbbbaaaaaaaaa",
	"fffbbbaaaaaaaaaa",
	"ffbbbaaaaaaaaaaa",
	"fbbbaaaaaaaaaaaa",
	"bbbaaaaaaaaaaaaa",
	"bbaaaaaaaaaaaaaa",
	"baaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
]

# EDGE base = mask 3 (TL+TR water, top edge): a straight coastline.
const _BASE_EDGE: PackedStringArray = [
	"cccccccccccccccc",
	"cccccccccccccccc",
	"cccccccccccccccc",
	"cccccccccccccccc",
	"cccccccccccccccc",
	"cccccccccccccccc",
	"ffffffffffffffff",
	"ffffffffffffffff",
	"bbbbbbbbbbbbbbbb",
	"bbbbbbbbbbbbbbbb",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
	"aaaaaaaaaaaaaaaa",
]

# DIAGONAL base = mask 9 (TL+BR water): two opposite wedges.
const _BASE_DIAGONAL: PackedStringArray = [
	"cccccccfffbbbaaa",
	"ccccccfffbbbaaaa",
	"cccccfffbbbaaaaa",
	"ccccfffbbbaaaaab",
	"cccfffbbbaaaaabb",
	"ccfffbbbaaaaabbb",
	"cfffbbbaaaaabbbf",
	"fffbbbaaaaabbbff",
	"ffbbbaaaaabbbfff",
	"fbbbaaaaabbbfffc",
	"bbbaaaaabbbfffcc",
	"bbaaaaabbbfffccc",
	"baaaaabbbfffcccc",
	"aaaaabbbfffccccc",
	"aaaabbbfffcccccc",
	"aaabbbfffccccccc",
]

# INNER base = mask 14 (TR+BL+BR water, TL is the only land corner): the
# CORNER wedge with land and water swapped.
const _BASE_INNER: PackedStringArray = [
	"aaaaaaabbbfffccc",
	"aaaaaabbbfffcccc",
	"aaaaabbbfffccccc",
	"aaaabbbfffcccccc",
	"aaabbbfffccccccc",
	"aabbbfffcccccccc",
	"abbbfffccccccccc",
	"bbbfffcccccccccc",
	"bbfffccccccccccc",
	"bfffcccccccccccc",
	"fffccccccccccccc",
	"ffcccccccccccccc",
	"fccccccccccccccc",
	"cccccccccccccccc",
	"cccccccccccccccc",
	"cccccccccccccccc",
]

const _BASE_MASKS := {
	"CORNER": 1,
	"EDGE": 3,
	"DIAGONAL": 9,
	"INNER": 14,
}

# ---------------------------------------------------------------------------


# TL | TR<<1 | BL<<2 | BR<<3 — the bit order documented at the top of this
# file and in autotile.gdshaderinc.
static func mask_of(tl: bool, tr: bool, bl: bool, br: bool) -> int:
	return int(tl) | (int(tr) << 1) | (int(bl) << 2) | (int(br) << 3)


# 90-degree clockwise rotation of a mask's corners: TL->TR->BR->BL->TL. Used
# both to derive the 14 tiles from 4 base shapes and by test_coast_tiles.gd
# to check the art and the bit order agree.
static func rotate_mask_cw(mask: int) -> int:
	var tl := (mask >> 2) & 1  # old BL -> new TL
	var tr := mask & 1  # old TL -> new TR
	var bl := (mask >> 3) & 1  # old BR -> new BL
	var br := (mask >> 1) & 1  # old TR -> new BR
	return tl | (tr << 1) | (bl << 2) | (br << 3)


# 90-degree clockwise rotation of a 16x16 row-string pixel map, matching
# rotate_mask_cw: new(x, y) = old(y, n-1-x).
static func _rotate_rows_cw(rows: PackedStringArray) -> PackedStringArray:
	var n := rows.size()
	var out := PackedStringArray()
	out.resize(n)
	for ny in n:
		var row := ""
		for nx in n:
			var old_x := ny
			var old_y := n - 1 - nx
			row += rows[old_y][old_x]
		out[ny] = row
	return out


# Which base family + rotation count produces `mask`'s art. Brute-forced from
# the 4 base masks (cheap: at most 4 rotations x 4 bases) so the mapping can
# never drift from rotate_mask_cw.
static func _family_and_rotation(mask: int) -> Array:
	for name in _BASE_MASKS.keys():
		var m: int = _BASE_MASKS[name]
		for rot in range(4):
			if m == mask:
				return [name, rot]
			m = rotate_mask_cw(m)
	push_error("coast_tiles: no base shape rotates to mask %d" % mask)
	return ["CORNER", 0]


static func _base_rows(name: String) -> PackedStringArray:
	match name:
		"CORNER":
			return _BASE_CORNER
		"EDGE":
			return _BASE_EDGE
		"DIAGONAL":
			return _BASE_DIAGONAL
		"INNER":
			return _BASE_INNER
	push_error("coast_tiles: unknown base family %s" % name)
	return _BASE_CORNER


static func _rows_for_mask(mask: int) -> PackedStringArray:
	var fr := _family_and_rotation(mask)
	var rows := _base_rows(fr[0])
	for _i in range(int(fr[1])):
		rows = _rotate_rows_cw(rows)
	return rows


# 16x16 RGBA8 coast tile for `mask` (0..15). Fully transparent for masks 0
# (all land) and 15 (all water) — the flat shader branches already look
# right there, so there is nothing to overlay.
static func tile_image(mask: int) -> Image:
	var img := Image.create(CELL_PX, CELL_PX, false, Image.FORMAT_RGBA8)
	if mask <= 0 or mask >= 15:
		return img
	var rows := _rows_for_mask(mask)
	for y in rows.size():
		var row: String = rows[y]
		for x in row.length():
			var ch := row[x]
			img.set_pixel(x, y, Color(_PALETTE[ch]))
	return img


static func _blit_cell(atlas: Image, img: Image, cell: int) -> void:
	var cx := (cell % ATLAS_COLS) * CELL_PX
	var cy := int(cell / float(ATLAS_COLS)) * CELL_PX
	atlas.blit_rect(img, Rect2i(0, 0, CELL_PX, CELL_PX), Vector2i(cx, cy))


# The 16 coast tiles packed into one square nearest-filtered atlas, cell
# index = mask, row-major (matches autotile.gdshaderinc's cell lookup and the
# `_blit_cell` convention already used by terrain_sprites.gd/ape_sprites.gd).
# Nearest filtering is a node/sampler property in Godot 4, not baked into the
# Image/ImageTexture — set `filter_nearest` on the shader uniform sampler (as
# terrain.gdshader already does for tile_atlas/terrain_ids) when wiring this
# atlas in.
static func build_atlas() -> ImageTexture:
	var side := ATLAS_COLS * CELL_PX
	var atlas := Image.create(side, side, false, Image.FORMAT_RGBA8)
	for mask in ATLAS_COLS * ATLAS_COLS:
		_blit_cell(atlas, tile_image(mask), mask)
	return ImageTexture.create_from_image(atlas)
