extends RefCounted
# Era structure sprite atlas for the village layer: one 32x32 block-art
# texture per settlement/landmark kind, painted from 32 row-strings of
# palette keys plus an auto 1px dark outline -- the same painter technique as
# TerrainSprites._sprite (row-string + palette) with the auto-outline pass of
# ApeSprites._build_cell (any transparent pixel touching an opaque one is
# outlined). Rows are authored top-down and left as painted here; the
# village layer flips them through SpriteSplit.for_quad when it binds them,
# because a plain MultiMesh quad draws image row 0 at the bottom (probe-
# verified; an earlier note claiming the opposite was wrong).
#
# This is the Phase 4 step 2 "era sets" contract from
# docs/superpowers/specs/2026-09-12-pixel-world-at-scale-design.md section 6:
# the enum, NAMES, CELL_PX and ATLAS_COLS below are load-bearing for
# village_layout.gd and the village layer built in parallel -- do not rename
# or reorder them.

enum {
	TENT,
	WINDBREAK,
	HEARTH,
	HUT,
	FENCE_H,
	FENCE_V,
	FIELD,
	GRANARY,
	HALL,
	PALISADE_H,
	PALISADE_V,
	PALISADE_CORNER,
	GATE,
	TOWER,
	MILL,
	FORGE,
	SCRIPTORIUM,
	BANNER,
	WELL,
	RUIN_BURNT,
	HUT_B,
	HUT_C,
	STALL,
	TENT_B,
}
const KIND_COUNT := 24
const ExtraRows = preload("res://scripts/structure_rows_extra.gd")
const CELL_PX := 32
const ATLAS_COLS := 8  # 8x8 grid of 32px cells = a square 256x256 atlas; cell index == kind

const NAMES: PackedStringArray = [
	"Tent",
	"Windbreak",
	"Hearth",
	"Hut",
	"FenceH",
	"FenceV",
	"Field",
	"Granary",
	"Hall",
	"PalisadeH",
	"PalisadeV",
	"PalisadeCorner",
	"Gate",
	"Tower",
	"Mill",
	"Forge",
	"Scriptorium",
	"Banner",
	"Well",
	"RuinBurnt",
	"HutRound",
	"Longhouse",
	"Stall",
	"Yurt",
]

# 32x32 row-string pixel maps per kind, indexed by the enum. '.' is
# transparent; every other character keys into PAL below. Authored with
# row 0 = top (roofline / sky) and the highest rows = ground, a 1px dark
# outline auto-applied around every opaque pixel's transparent neighbours,
# and a ground shadow near the base of every silhouette.
const _ROWS: Array = [
	# TENT
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"...............KK...............",
		"..............KbbK..............",
		"..............KbbK..............",
		"........KKKKKKKbbKKKKKKK........",
		".......KhhhhhhhhhhhhhhhhK.......",
		".......KhhhhhhhhhhhhhhhhK.......",
		"......KhhhhhhhhhhhhhhhhhhK......",
		"......KhhhhhhhhhhhhhhhhhhK......",
		".....KTTTTTTTTTTTTTTTTTTTTK.....",
		".....KTTTTTTTTTTTTTTTTTTTTK.....",
		"....KhhhhhhhhhhhhhhhhhhhhhhK....",
		"....KhhhhhhhhhhhhhhhhhhhhhhK....",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"..KhhhhhhhhhhhhhhhhhhhhhhhhhhK..",
		"..KhhhhhhhhhhhhhhhhhhhhhhhhhhK..",
		".KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK.",
		".KTTTTTTTTTTTTTTTTTTTTTTTTTTTTK.",
		"KhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhK",
		"KhhhhhhhhhhhhbbbbbbhhhhhhhhhhhhK",
		"KhhhhhhhhhhhhbbbbbbhhhhhhhhhhhhK",
		"TTTTTTTTTTTTTbKKKKbTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTbKKKKbTTTTTTTTTTTTT",
		"TTTTTTTTTTTTTbKKKKbTTTTTTTTTTTTT",
		"KKKKKKkkkkkkkkkkkkkkkkkkkkKKKKKK",
		"......KKKKKKKKKKKKKKKKKKKK......",
		"................................",
	],
	# WINDBREAK
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"..............KK................",
		".............KbbK...............",
		".............KbbK...............",
		".............KbbK...............",
		"............KKbbK.KK............",
		"...........KBBbbKKBBK...........",
		"...........KBBbbKKBBK...........",
		"...........KBBbbKKBBK...........",
		"........KKKKBBbbKKBBKKKK........",
		".......KTTTTTTTTTTTTTTTTK.......",
		".......KTTTTTTTTTTTTTTTTK.......",
		".......KBBKKBBbbKKKKKKBBK.......",
		".......KBBKKBBbbK....KBBK.......",
		".......KBBK.KKbbK....KBBK.......",
		"......KKBBKKKKbbKKKKKKBBKK......",
		".....KTTTTTTTTTTTTTTTTTTTTK.....",
		"....KKTTTTTTTTTTTTTTTTTTTTKK....",
		"...KBBKKKKKKKKbbKKKKKKBBKKBBK...",
		"...KBBKKKKKKKKbbKKKKKKBBKKBBK...",
		"...KBBkkkkkkkkbbkkkkkkkkkkBBK...",
		"...KBBkkkkkkkkkkkkkkkkkkkkBBK...",
		"...KBBKKKKKKKKKKKKKKKKKKKKBBK...",
		"...KBBK..................KBBK...",
	],
	# HEARTH
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"...............KK...............",
		"..............KyyK..............",
		"..............KyyK..............",
		".............KyyyyK.............",
		".............KyyyyK.............",
		".............KoyyoK.............",
		"............KooyyooK............",
		"............KooyyooK............",
		"............KoooooooK...........",
		"...........KoooooooooK..........",
		"...........KoooooooooK..........",
		"...........KrooooooorK..........",
		".........KKKKooooooKKKK.........",
		"........KSsSSKooooKSSsSK........",
		".......KSSsSSSKKKKSSSsSSK.......",
		".......KSsSSSkkkkkkSSSSsK.......",
		".......KSSSSSkkkkkkSSsSSK.......",
		"..KKKK.KsSSSSSSSSSSSSSSsK.KKKK..",
		".KbbbbK.KSSSSsSSSSsSSSSK.KbbbbK.",
		".KBBBBK..KKSSSSSSSSSSKK..KBBBBK.",
		".KbbbbK....KKKKKKKKKK....KbbbbK.",
		"..KKKK....................KKKK..",
		"................................",
		"................................",
		"................................",
		"................................",
	],
	# HUT
	[
		"................................",
		"................................",
		"................................",
		".............KKKKKK.............",
		"............KbbbbbbK............",
		"..........KKKbbbbbbKKK..........",
		".........KTTTTTTTTTTTTK.........",
		".........KTTTTTTTTTTTTK.........",
		".......KKKTTTTTTTTTTTTKKK.......",
		"......KttttttttttttttttttK......",
		"......KttttttttttttttttttK......",
		".....KKttttttttttttttttttKK.....",
		"....KTTTTTTTTTTTTTTTTTTTTTTK....",
		"....KTTTTTTTTTTTTTTTTTTTTTTK....",
		"....KTTTTTTTTTTTTTTTTTTTTTTK....",
		"...KttttttttttttttttttttttttK...",
		"...KttttttttttttttttttttttttK...",
		"...KttttttttttttttttttttttttK...",
		"..KBBBBBBBBBBBBBBBBBBBBBBBBBBK..",
		"..KbbbbbbbbbbbbbbbbbbbbbbbbbbK..",
		"..KbbbbbbbbbbbbbbbbbbbbbbbbbbK..",
		"..KbbbbbbbbbbbbbbbbbbbbbbbbbbK..",
		"...KKKKKKKKKKBBBBBBKKKKKKKKKK...",
		"............KKKKKKKK............",
		"............KKKKKKKK............",
		"............KKKKKKKK............",
		"............KKKKKKKK............",
		"............KKKKKKKK............",
		"...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
		"..KkkkkkkkkkkKKKKKKkkkkkkkkkkK..",
		"..KkkkkkkkkkkkkkkkkkkkkkkkkkkK..",
		"...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
	],
	# FENCE_H
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"KKK............KKK...........KKK",
		"bbbK..........KbbbK.........Kbbb",
		"bbbKKKKKKKKKKKKbbbKKKKKKKKKKKbbb",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"bbbKKKKKKKKKKKKbbbKKKKKKKKKKKbbb",
		"bbbK..........KbbbK.........Kbbb",
		"bbbK..........KbbbK.........Kbbb",
		"bbbKKKKKKKKKKKKbbbKKKKKKKKKKKbbb",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"bbbKKKKKKKKKKKKbbbKKKKKKKKKKKbbb",
		"bbbkkkkkkkkkkkkbbbkkkkkkkkkkkbbb",
		"bbbkkkkkkkkkkkkbbbkkkkkkkkkkkbbb",
		"bbbKKKKKKKKKKKKbbbKKKKKKKKKKKbbb",
		"KKK............KKK...........KKK",
		"................................",
	],
	# FENCE_V
	[
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbKKKKKKKKKKKKKbbbKKKKKKKKKKKKK",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"bbbKKKKKKKKKKKKKbbbKKKKKKKKKKKKK",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbKKKKKKKKKKKKKbbbKKKKKKKKKKKKK",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"bbbKKKKKKKKKKKKKbbbKKKKKKKKKKKKK",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK...........KbbbK............",
		"bbbK......KKKKKKbbbK............",
		"bbbK.....KkkkkkkbbbK............",
		"bbbK.....KkkkkkkbbbK............",
		"bbbK.....KkkkkkkbbbK............",
	],
	# FIELD
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
		"gTgggTgggTgggTgggTgggTgggTgggTgg",
		"gggggggggggggggggggggggggggggggg",
		"gggggggggggggggggggggggggggggggg",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
		"gTgggTgggTgggTgggTgggTgggTgggTgg",
		"gggggggggggggggggggggggggggggggg",
		"gggggggggggggggggggggggggggggggg",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
		"gTgggTgggTgggTgggTgggTgggTgggTgg",
		"gggggggggggggggggggggggggggggggg",
		"gggggggggggggggggggggggggggggggg",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
		"gTgggTgggTgggTgggTgggTgggTgggTgg",
		"gggggggggggggggggggggggggggggggg",
		"gggggggggggggggggggggggggggggggg",
		"dddddddddddddddddddddddddddddddd",
		"dddddddddddddddddddddddddddddddd",
	],
	# GRANARY
	[
		"................................",
		"................................",
		"................................",
		".........KKKKKKKKKKKKKK.........",
		"........KTTTTTTTTTTTTTTK........",
		"........KTTTTTTTTTTTTTTK........",
		"......KKKTTTTTTTTTTTTTTKKK......",
		".....KttttttttttttttttttttK.....",
		".....KttttttttttttttttttttK.....",
		"....KKttttttttttttttttttttKK....",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"....KKKKKKKKKKKKKKKKKKKKKKKK....",
		".....KKKKKKKKKKKKKKKKKKKKKK.....",
		"....KTTTTTTTTTTTTTTTTTTTTTTK....",
		"....KBBBBBBBBBBBBBBBBBBBBBBK....",
		"....KBBBBBBBBBBBBBBBBBBBBBBK....",
		"....KBBBBBBBBBbbbbBBBBBBBBBK....",
		"....KBBBBBBBBBbbbbBBBBBBBBBK....",
		"....KBBBBBBBBBbbbbBBBBBBBBBK....",
		"....KBBBBBBBBBbbbbBBBBBBBBBK....",
		"...KbBBBBBBBBBbbbbBBBBBBBBBbK...",
		"...KbbbKKKKKKKKKKKKKKKKKKbbbK...",
		"...KbbbK................KbbbK...",
		"...KbbbK................KbbbK...",
		"...KbbbKKKKKKKKKKKKKKKKKKbbbK...",
		"...KbbbkkkkkkkkkkkkkkkkkkbbbK...",
		"...KbbbkkkkkkkkkkkkkkkkkkbbbK...",
		"...KbbbKKKKKKKKKKKKKKKKKKbbbK...",
		"....KKK..................KKK....",
		"................................",
	],
	# HALL
	[
		"................................",
		"................................",
		"................................",
		"......KKKKKKKKKKKKKKKKKKKK......",
		".....KTTTTTTTTTTTTTTTTTTTTK.....",
		".....KTTTTTTTTTTTTTTTTTTTTK.....",
		"...KKKTTTTTTTTTTTTTTTTTTTTKKK...",
		"..KttttttttttttttttttttttttttK..",
		"..KttttttttttttttttttttttttttK..",
		".KKttttttttttttttttttttttttttKK.",
		"KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK",
		"KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK",
		"KTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTK",
		".KBBBBBBBBBBBBBBBBBBBBBBBBBBBBK.",
		".KBBBBBBBBBBBBBBBBBBBBBBBBBBBBK.",
		".KBBBBBBBBBBbbbbbbbbBBBBBBBBBBK.",
		".KBBBBBBBBBBbbbbbbbbBBBBBBBBBBK.",
		".KBBBBBBBBBBBBBBBBBBBBBBBBBBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		".KBBBKKKKKBBBBBBBBBBBBKKKKKBBBK.",
		"KkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkK",
		"KkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkK",
		".KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
		"................................",
		"................................",
	],
	# PALISADE_H
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		".K..K..K..K..K..K..K..K..K..K..K",
		"KbKKbKKbKKbKKbKKbKKbKKbKKbKKbKKb",
		"KbKKbKKbKKbKKbKKbKKbKKbKKbKKbKKb",
		"BBKBBKBBKBBKBBKBBKBBKBBKBBKBBKBB",
		"BBKBBKBBKBBKBBKBBKBBKBBKBBKBBKBB",
		"BBbBBbBBbBBbBBbBBbBBbBBbBBbBBbBB",
		"BBbBBbBBbBBbBBbBBbBBbBBbBBbBBbBB",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
		"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
	],
	# PALISADE_V
	[
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
		"......KKKKbbBBbbbbbbbbbbbbbbbbK.",
		"......KKBBBBBBbbbbbbbbbbbbbbbbK.",
		".....KbbBBBBBBbbbbbbbbbbbbbbbbK.",
	],
	# PALISADE_CORNER
	[
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		"........KKbbbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		"........KKbbbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		"........KKbbbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		"........KKbbbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		"........KKbbbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		".......KBBBBbbbbbbbbbbbbbbbbbbbb",
		"KK.KK.KKKKbbbbbbbbbbbbbbbbbbbbbb",
		"BBKBBKBBBBBBBBbBBbBBbBBbBBbBBbBB",
		"BBKBBKBBBBBBBBbBBbBBbBBbBBbBBbBB",
		"BBbBBbSSSSSSBBbBBbBBbBBbBBbBBbBB",
		"BBbBBbSSSSSSBBbBBbBBbBBbBBbBBbBB",
		"bbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbSSSSSSbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbBBBBbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbBBBBbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbBBBBbbbbbbbbbbbbbbbbbbbb",
		"bbbbbbbbBBBBbbbbbbbbbbbbbbbbbbbb",
	],
	# GATE
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"..KKKKKK................KKKKKK..",
		".KBBBBBBK..............KBBBBBBK.",
		".KBBBBBBKKKKKKKKKKKKKKKKBBBBBBK.",
		".KBBBBBBTTTTTTTTTTTTTTTTBBBBBBK.",
		"KKBBBBBBBBBBBBBBBBBBBBBBBBBBBBKK",
		"bbBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb",
		"bbBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"bbbbbbbbbbKnnnnnnnnnnKbbbbbbbbbb",
		"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
		"kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk",
	],
	# TOWER
	[
		"....KKKKKKKKKKKKKKKKKKKKKKKK....",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"...KTTTTTTTTTTTTTTTTTTTTTTTTK...",
		"....KbbbbbbbbbbbbbbbbbbbbbbK....",
		"....KbbbbbbbbbbbbbbbbbbbbbbK....",
		"....KbbbbbbbbbbbbbbbbbbbbbbK....",
		"....KbbbbbbbbbbbbbbbbbbbbbbK....",
		"....KbbbbbbbbbbbbbbbbbbbbbbK....",
		".....KTTTTTTTTTTTTTTTTTTTTK.....",
		".....KBBBBBBBBBBBBBBBBBBBBK.....",
		".....KBBBBBBnnnBBBBBBBBBBBK.....",
		".....KBBBBBBnnnBBBBBBBBBBBK.....",
		"......KKKbbbnnnKKKKbbbbKKK......",
		"........KbbbbKKKKKKbbbbK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KbbbbKKKKKKbbbbK........",
		"........KbbbbKKKKKKbbbbK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KbbbbKKKKKKbbbbK........",
		"........KbbbbKKKKKKbbbbK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KbbbbKKKKKKbbbbK........",
		"........KbbbbKKKKKKbbbbK........",
		"........KBBBBBBBBBBBBBBK........",
		"........KBBBBBBBBBBBBBBK........",
		".......KkbbbbkkkkkkbbbbkK.......",
		".......KkbbbbkkkkkkbbbbkK.......",
		".......KkkkkkkkkkkkkkkkkK.......",
		"........KKKKKKKKKKKKKKKK........",
	],
	# MILL
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"..................KKKKKKKKK.....",
		".................KTTTTTTTTTK....",
		".................KTTTTTTTTTK....",
		".......KK......KKKTTTTTTTTTKKK..",
		"......KbbK....KTTTTTTTTTTTTTTTK.",
		"......KbbK....KTTTTTTTTTTTTTTTK.",
		"...KKKKbbKKKK.KTTTTTTTTTTTTTTTK.",
		"..KSSSSbbSSSSK.KBBBBBBBBBBBBBK..",
		"..KSSSSbbSSSSK.KBBBBBBBBBBBBBK..",
		"..KSSSSbbSSSSK.KBBBBBBBBBBBBBK..",
		"KKKSSSsbbsSSSKKKBBBBBBBBBBBBBK..",
		"bbbbbbbbbbbbbbbbBBBBBBBBBBBBBK..",
		"bbbbbbbbbbbbbbbbBBBBBBBBBBBBBK..",
		"KKKSSSsbbsSSSKKKBBBBBBBBBBBBBK..",
		"..KSSSSbbSSSSK.KBBBBBBBBBBBBBK..",
		"..KSSSSbbSSSSK.KBBBBBBBBBBBBBK..",
		"..KSSSSbbSSSSK.KBBBBBBBBBBBBBK..",
		".KwwwwwwwwKKK..KBBBBBBBBBBBBBK..",
		".KwwwwwwwwK....KBBBBBBBBBBBBBK..",
		".KwwwwwwwwK....KBBBBBBBBBBBBBK..",
		".KwwwwwwwwK....KBBBBBBBBBBBBBK..",
		".KwwwwwwwwK....KBBBBBwwwwwwBBK..",
		".KwwwwwwwwKKKKKKBBBBBwwwwwwBBKK.",
		"KkkkkkkkkkkkkkkkkkkkkwwwwwwkkkkK",
		"KkkkkkkkkkkkkkkkkkkkkwwwwwwkkkkK",
		"KkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkK",
		".KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.",
	],
	# FORGE
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		".....KKKKKKKKKKKKKKKKKKKKKK.....",
		"....KTTTTTTTTTTTTTTTTTTTTTTK....",
		"...KKTTTTTTTTTTTTTTTTTTTTTTKK...",
		"..KbbTTTTTTTTTTTTTTTTTTTTTTbbK..",
		"..KbbbbbbbbbbbbbbbbbbbbbbbbbbK..",
		"..KbbbbbbbbbbbbbbbbbbbbbbbbbbK..",
		"..KbbbbbbbbbbbbyybbbbbbbbbbbbK..",
		"..KbbbbKKKKKKKKyyKKKKKKKKbbbbK..",
		"..KbbbbK......KyyK......KbbbbK..",
		"..KbbbbK.....KooooK.....KbbbbK..",
		"..KbbbbK..KKKKooooKKKK..KbbbbK..",
		"..KbbbbK.KSSSSooooSSSSK.KbbbbK..",
		"..KbbbbK.KSSSSooooSSSSK.KbbbbK..",
		"..KbbbbK.KSSnnnnnnnnSSK.KbbbbK..",
		"..KbbbbK.KSSnnnnnnnnSSK.KbbbbK..",
		"..KbbbbK.KSSssnnnnnnSSK.KbbbbK..",
		"..KbbbbK.KSSssnnnnnnSSK.KbbbbK..",
		"..KbbbbKKssssssssnnnSSK.KbbbbK..",
		"..KbbbbKKssssssssnnnSSK.KbbbbK..",
		"..KbbbbKKssssssssSSSSSK.KbbbbK..",
		"..KbbbbKKKSSSSSSSSSSSSKKKbbbbK..",
		".KkkkkkkkkkkkkkkkkkkkkkkkkkkkkK.",
		".KkkkkkkkkkkkkkkkkkkkkkkkkkkkkK.",
		".KkkkkkkkkkkkkkkkkkkkkkkkkkkkkK.",
		"..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
	],
	# SCRIPTORIUM
	[
		"................................",
		"................................",
		"................................",
		"....................KKKKKKKK....",
		"...................KeeeeeeeeK...",
		"...................KeeeeeeeeK...",
		"...................KeTTTTTTeK...",
		"......KKKKKKKKKKKKKKeeeeeeeeK...",
		".....KsssssssssssssseTTTTTTeK...",
		".....KsssssssssssssseeeeeeeeK...",
		"...KKKssssssssssssssssbbssKKK...",
		"..KSSSSSSSSSSSSSSSSSSSbbSSSSSK..",
		"..KSSSSSSSSSSSSSSSSSSSbbSSSSSK..",
		"..KSSSSSSSSSSSSSSSSSSSbbSSSSSK..",
		"...KssssssssssssssssssbbssssK...",
		"...KssssssssssssssssssssssssK...",
		"...KssssssssssssssssssssssssK...",
		"...KssssssssssssssssssssssssK...",
		"...KssssssssssssssssssssssssK...",
		"...KssssssssssssssssssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"...KssssssssKKKKKKKKssssssssK...",
		"..KKssssssssKKKKKKKKssssssssKK..",
		".KkkkkkkkkkkkkkkkkkkkkkkkkkkkkK.",
		".KkkkkkkkkkkkkkkkkkkkkkkkkkkkkK.",
		".KkkkkkkkkkkkkkkkkkkkkkkkkkkkkK.",
		"..KKKKKKKKKKKKKKKKKKKKKKKKKKKK..",
	],
	# BANNER
	[
		"................................",
		"................................",
		"...............KK...............",
		"..............KbbKKKKKKKKKKK....",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbrrrrrrrrrSSK...",
		"..............KbbKKKKKKKKKKK....",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"..............KbbK..............",
		"............KKKbbKKK............",
		"...........KkkkbbkkkK...........",
		"...........KkkkkkkkkK...........",
		"............KKKKKKKK............",
	],
	# WELL
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		".....KKKKKKKKKKKKKKKKKKKKKK.....",
		"....KBBBBBBBBBBBBBBBBBBBBBBK....",
		"....KBBBBBBBBBBBBBBBBBBBBBBK....",
		"....KbbKKKKKKKKTTKKKKKKKKbbK....",
		"....KbbK......KTTK......KbbK....",
		"....KbbK......KTTK......KbbK....",
		"....KbbK......KTTK......KbbK....",
		"....KbbK.....KKTTKK.....KbbK....",
		"....KbbK....KSSSSSSK....KbbK....",
		"....KbbK....KSSSSSSK....KbbK....",
		"....KbbKKKKKKSSSSSSKKKKKKbbK....",
		"....KbbSSSSSSSSSSSSSSSSSSbbK....",
		".....KSSSSSSSSSSSSSSSSSSSSK.....",
		".....KssssssssssssssssssssK.....",
		".....KsssnnnnnnnnnnnnnnsssK.....",
		".....KsssnnnnnnnnnnnnnnsssK.....",
		".....KsssnnnnnnnnnnnnnnsssK.....",
		".....KsssnnnnnnnnnnnnnnsssK.....",
		".....KsssnnnnnnnnnnnnnnsssK.....",
		"....KKssssssssssssssssssssKK....",
		"...KkksssssssssssssssssssskkK...",
		"...KkkkkkkkkkkkkkkkkkkkkkkkkK...",
		"...KkkkkkkkkkkkkkkkkkkkkkkkkK...",
		"....KKKKKKKKKKKKKKKKKKKKKKKK....",
		"................................",
	],
	# RUIN_BURNT
	[
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"................................",
		"............KKK.................",
		"...........KKKKK................",
		"...........KKKKK.....KKK........",
		"...........KKKKK....KKKKK.......",
		"........KKKKKKKK....KKKKK.......",
		".......KKKKKKKKK....KKKKK.......",
		".......KKKKKKKKK....KKKKK.......",
		".......KKKKKKKKK....KKKKK.......",
		".......KKKKKKKKK.KK.KKKKK.......",
		".......KKKKKKKKKKyyKKKKKK.......",
		"......KKKKKKKKKKKyyKKKKKKK......",
		".....KnnKKKnKKKnnnnnnKKKnnK.....",
		".....KnnKKKnKKKnnnnnnKKKnnK.....",
		".....KnnKKKnnnooonnnnKKKnnK.....",
		".....KnnKKKnnnooonnnnKKKnnK.....",
		".....KnnnnnnnnooonnnnnnnnnK.....",
		".....KnnnnnnnnnnnnnoonnnnnK.....",
		".....KnnnnnnnnnnnnnoonnnnnK.....",
		".....KnnnnnnnnnnnnnnnnnnnnK.....",
		"...KKKnnnnnnnnnnnnnnnnnnnnKKK...",
		"..KkkkkkkkkkkkkkkkkkkkkkkkkkkK..",
		"..KkkkkkkkkkkkkkkkkkkkkkkkkkkK..",
		"...KKKKKKKKKKKKKKKKKKKKKKKKKK...",
	],
]

const PAL: Dictionary = {
	"K": "14100f",
	"b": "4a2f1e",
	"B": "7a4c2c",
	"t": "c9a24a",
	"T": "a67f2e",
	"s": "6b6673",
	"S": "494452",
	"o": "d98f4a",
	"y": "f2c14e",
	"r": "c23a34",
	"w": "2f6f9c",
	"d": "5a3c22",
	"g": "6fa040",
	"h": "e8e2d0",
	"k": "0e0d10",
	"n": "241f26",
	"e": "f4f4f4",
}

# --- animated kinds: hearth flame, forge glow, ember-lit ruin -------------
# Phase 1 pixel overrides ([x, y, key]) applied ON TOP of the base rows,
# touching only flame/ember pixels -- walls, roofs, footprint, enum and
# NAMES are exactly the base's, same discipline as
# BuildingSprites._LIFT_BLOCKS (Fire/Metalworking).
const ANIMATED_KINDS: PackedInt32Array = [HEARTH, FORGE, RUIN_BURNT]
const _LIFT: Dictionary = {
	# Hearth: the flame tip climbs two rows (with its own outline cap and
	# ring, tapering the same way the base art's tip does) and the existing
	# tip turns white-hot; the wide base brightens from amber to yellow at
	# its shoulders.
	HEARTH:
	[
		[15, 4, "K"],
		[16, 4, "K"],
		[14, 5, "K"],
		[15, 5, "y"],
		[16, 5, "y"],
		[17, 5, "K"],
		[15, 6, "y"],
		[16, 6, "y"],
		[15, 7, "e"],
		[16, 7, "e"],
		[14, 13, "y"],
		[17, 13, "y"],
	],
	# Forge: the glow core whitens and the surrounding coals brighten from
	# amber to yellow.
	FORGE:
	[
		[15, 13, "e"],
		[16, 13, "e"],
		[15, 14, "e"],
		[16, 14, "e"],
		[15, 15, "e"],
		[16, 15, "e"],
		[14, 16, "y"],
		[15, 16, "y"],
		[16, 16, "y"],
		[17, 16, "y"],
		[14, 17, "y"],
		[15, 17, "y"],
		[16, 17, "y"],
		[17, 17, "y"],
		[14, 18, "y"],
		[15, 18, "y"],
		[16, 18, "y"],
		[17, 18, "y"],
		[14, 19, "y"],
		[15, 19, "y"],
		[16, 19, "y"],
		[17, 19, "y"],
	],
	# Ruin (burnt): the crown ember whitens, a fresh coal glows through a gap
	# in the collapsed beams, and two of the base embers brighten to yellow.
	RUIN_BURNT:
	[
		[17, 18, "e"],
		[18, 18, "e"],
		[17, 19, "e"],
		[18, 19, "e"],
		[16, 21, "o"],
		[17, 21, "o"],
		[15, 22, "y"],
		[16, 22, "y"],
		[15, 23, "y"],
		[16, 23, "y"],
		[20, 25, "y"],
		[20, 26, "y"],
	],
}


static func is_animated(kind: int) -> bool:
	return ANIMATED_KINDS.has(kind)


# Row-string + palette painter, identical in shape to TerrainSprites._sprite:
# builds the CELL_PX square, paints every non-'.' character from `pal`, then
# applies overrides (sparse [x, y, key] triples, phase 1 only) before the
# auto-outline pass so a lift can introduce a brand new ember pixel next to
# already-outlined art without leaving a gap.
static func _paint(rows: Array, overrides: Array) -> Image:
	var img := Image.create(CELL_PX, CELL_PX, false, Image.FORMAT_RGBA8)
	img.fill(Color(0, 0, 0, 0))
	if rows.size() != CELL_PX:
		push_error("pixel map has %d rows, want %d" % [rows.size(), CELL_PX])
		return img
	for y in rows.size():
		var row: String = rows[y]
		if row.length() != CELL_PX:
			push_error("pixel map row %d has %d chars, want %d" % [y, row.length(), CELL_PX])
			continue
		for x in row.length():
			var c := row[x]
			if c != ".":
				img.set_pixel(x, y, Color(PAL[c]))
	for o in overrides:
		var ox: int = o[0]
		var oy: int = o[1]
		var okey: String = o[2]
		img.set_pixel(ox, oy, Color(PAL[okey]))
	return img


# Rows for a kind: the base set lives in _ROWS, later kinds in
# structure_rows_extra.gd.
static func rows_of(kind: int) -> Array:
	if kind < _ROWS.size():
		return _ROWS[kind]
	return ExtraRows.ROWS[kind - ExtraRows.BASE_COUNT]


static func kind_image(kind: int) -> Image:
	return _paint(rows_of(kind), [])


static func build_variant_image(kind: int, phase: int) -> Image:
	if phase % 2 == 0 or not is_animated(kind):
		return kind_image(kind)
	return _paint(rows_of(kind), _LIFT[kind])


static func build_variant(kind: int, phase: int) -> ImageTexture:
	return ImageTexture.create_from_image(build_variant_image(kind, phase))


# Camp (era 0): tents, windbreak, hearth. Thatch (era 1): huts, fences,
# fields, granary, well, and the burnt ruin left by a raid. Timber/stone
# (era 2): everything else -- halls, palisade, gate, tower, mill, forge,
# scriptorium, banners.
static func era_of(kind: int) -> int:
	match kind:
		TENT, TENT_B, WINDBREAK, HEARTH:
			return 0
		HUT, HUT_B, HUT_C, FENCE_H, FENCE_V, FIELD, GRANARY, WELL, RUIN_BURNT, STALL:
			return 1
		_:
			return 2


# Every kind's image packed into one square nearest-filtered atlas, cell
# index == kind, row-major -- same square-grid contract and _blit_cell
# geometry as TerrainSprites.build_atlas (required by the Metal MultiMesh
# path: extreme-aspect atlases corrupt). Cells already carry kind_image's
# so a cell's centre pixel matches kind_image(k)'s centre pixel directly.
static func build_atlas() -> ImageTexture:
	var side := ATLAS_COLS * CELL_PX
	var atlas := Image.create(side, side, false, Image.FORMAT_RGBA8)
	for k in KIND_COUNT:
		_blit_cell(atlas, kind_image(k), k)
	return ImageTexture.create_from_image(atlas)


static func _blit_cell(atlas: Image, img: Image, cell: int) -> void:
	var cx := (cell % ATLAS_COLS) * CELL_PX
	var cy := int(cell / float(ATLAS_COLS)) * CELL_PX
	atlas.blit_rect(img, Rect2i(0, 0, CELL_PX, CELL_PX), Vector2i(cx, cy))


static func opaque_pixels(img: Image) -> int:
	var count := 0
	for y in img.get_height():
		for x in img.get_width():
			if img.get_pixel(x, y).a > 0.5:
				count += 1
	return count
