//! Pin deterministic state hashes at fixed ticks of the minimal scenario.
//!
//! When this test fails because hashes mismatch, the dev must either:
//! (a) confirm the change is intentional and update the constants below, or
//! (b) fix the regression. Hash changes must be deliberate.

use anabios_core::scenario::Scenario;
use anabios_core::snapshot::state_hash;
use anabios_core::tick::step;

const SCENARIO: &str = include_str!("../../../scenarios/minimal.toml");

/// Hashes at (tick, hash). Generated by running this test once with the
/// `UPDATE_HASHES=1` env var (see below); copy the printed values into here.
// Refreshed 2026-07-17: added BiomeCell.env climate field + World.biome_adaptation
// flag, then tuned the climate to low frequency (large zones for habitat selection).
// Behavior is unchanged with the flag off (env is unread; terrain/biomass generation
// is byte-identical) — only the serialized env bytes changed, so all three hashes moved.
// Refreshed 2026-07-17 (2): MAX_POPULATION raised 2_000 → 10_000 (design's 10k
// budget) and became a per-world field (`World::max_population`, scenario-
// overridable). minimal.toml pins 2000, restoring pre-raise behavior; all three
// hashes moved because the serialized World layout gained the new field.
// Refreshed 2026-07-18: added World.{world_size,biome_res,hash_res} runtime
// dimension fields (unused; behaviour identical at defaults, only serialized
// layout grew).
// Refreshed 2026-07-18: BiomeField/pheromone grid became dimension-aware
// (byte-identical at default res=128).
// Refreshed 2026-07-18: UniformSpatialHash dimension-aware (skip, no layout
// change) + PheromoneField gained world_size (serialized) — byte-identical
// at defaults.
// Refreshed 2026-07-18: added World.living_biome flag (off = byte-identical;
// only serialized layout grew).
// Refreshed 2026-07-18: added World.season_period (off = byte-identical).
// Refreshed 2026-07-18: added World.cultural_inventions flag + renamed genome
// slot 42 to Inventiveness (flag off = byte-identical; only serialized layout
// grew — the slot value semantics are unchanged).
// Refreshed 2026-07-19: the cultural-inventions ratchet is replaced by the
// full invention tree — MEME_CHANNELS widened 8→18 (inventions ride meme
// channels), BiomeCell.pollution, World.cultural_inventions renamed to
// inventions_enabled, genome slot 42 back to reserved, CodexState invention
// latches. Flag-off behavior unchanged (identity multipliers at mask 0, zero
// invention RNG draws); serialized layout changed, so all three hashes moved.
// Refreshed 2026-07-19 (2): MemeSweep no longer tracks invention channels
// (InventionAdopted reports those sweeps explicitly). Simulation physics
// unchanged; only codex bookkeeping/serialized bytes differ — tick 1000 moved
// because minimal's grazers evolve a Communicator by then.
// Refreshed 2026-07-19 (3): `inherit_meme` now skips the invention channels'
// jitter draws when `inventions_enabled` is false, restoring the pre-tree
// 8-channel RNG draw count for flag-off scenarios (the widening had silently
// drawn 10 extra jitters per Communicator birth even with the flag off). Only
// tick 1000 moved — minimal's grazers evolve a Communicator between ticks 100
// and 1000, and this undoes that trajectory perturbation for every non-
// invention culture scenario.
// Refreshed 2026-07-19 (4): cognitive layer Phase 1 — AgentBuffers gained the
// realized-IQ phenotype fields (iq / iq_enrich_acc / iq_enrich_ticks) and
// FORMAT_VERSION bumped to 6. `cognition_enabled` defaults off, so IQ stays 0
// for every agent (metabolic multiplier is exact identity) and behavior is
// unchanged — but the serialized layout grew from tick 0, so all three hashes
// moved by layout only (the tick-0 move proves there is no trajectory change).
// Refreshed 2026-07-19 (5): cognitive layer Phase 3 — MEME_CHANNELS widened
// 18→20 for the maladaptive-practice block (channels 18-19); FORMAT_VERSION 7.
// `cognition_enabled` off ⇒ practice channels stay 0, draw no jitter (inherit_meme
// gates them on the flag), and no reproductive effect applies — behavior
// unchanged; only the serialized meme vector grew, so all three hashes moved by
// layout (tick-0 move again proves no trajectory change).
const GOLDEN: &[(u64, u64)] =
    &[(0, 0x0e6dcdf26e39bcbd), (100, 0xb5a371c1c48346a4), (1000, 0x04f2eaad01e93df7)];

#[test]
fn minimal_scenario_matches_golden_hashes() {
    let scenario = Scenario::parse_toml(SCENARIO).expect("parse minimal scenario");
    let mut world = scenario.instantiate();

    let mut idx = 0;
    let mut observed: Vec<(u64, u64)> = Vec::new();
    let max_tick = GOLDEN.iter().map(|(t, _)| *t).max().unwrap_or(0);

    while world.tick <= max_tick {
        while idx < GOLDEN.len() && GOLDEN[idx].0 == world.tick {
            let h = state_hash(&world);
            observed.push((world.tick, h));
            idx += 1;
        }
        if world.tick == max_tick {
            break;
        }
        step(&mut world);
    }

    if std::env::var("UPDATE_HASHES").is_ok() {
        println!("// regenerated hashes:");
        for (t, h) in &observed {
            println!("    ({}, 0x{:016x}),", t, h);
        }
        return;
    }

    for ((expected_tick, expected_hash), (got_tick, got_hash)) in GOLDEN.iter().zip(&observed) {
        assert_eq!(expected_tick, got_tick, "tick mismatch");
        assert_eq!(
            *expected_hash, *got_hash,
            "hash drift at tick {expected_tick}: expected 0x{expected_hash:016x}, got 0x{got_hash:016x}.\n\
             If this change is intentional, rerun with UPDATE_HASHES=1 and copy the printed values.",
        );
    }
}
