//! Pin deterministic state hashes at fixed ticks of the minimal scenario.
//!
//! When this test fails because hashes mismatch, the dev must either:
//! (a) confirm the change is intentional and update the constants below, or
//! (b) fix the regression. Hash changes must be deliberate.

use anabios_core::scenario::Scenario;
use anabios_core::snapshot::{load_from_bytes, save_to_bytes, state_hash};
use anabios_core::tick::step;

/// The gene↔tech coupling showcase must survive a save→load→step round-trip:
/// stepping a freshly-loaded world one tick must reproduce the same state hash
/// as stepping the original. Guards the new `gene_tech_coupling` flag (and the
/// coupled effect sites / discovery arm it drives) against any hidden state that
/// serialization would drop — the serde-skip replay footgun.
#[test]
fn gene_tech_coupling_survives_save_load_step() {
    const COUPLED: &str = include_str!("../../../scenarios/tech-gene-coupling.toml");
    let mut world = Scenario::parse_toml(COUPLED).expect("parse coupled scenario").instantiate();
    assert!(world.gene_tech_coupling, "scenario must enable coupling");
    // Warm the world up so inventions are discovered and the coupled paths run.
    for _ in 0..300 {
        step(&mut world);
    }
    let bytes = save_to_bytes(&world).expect("save");
    let mut reloaded = load_from_bytes(&bytes).expect("load");
    assert_eq!(state_hash(&world), state_hash(&reloaded), "load must restore identical state");
    // One more tick on both must land on the same hash.
    step(&mut world);
    step(&mut reloaded);
    assert_eq!(
        state_hash(&world),
        state_hash(&reloaded),
        "coupled world diverged after save→load→step (hidden non-serialized state?)",
    );
}

const SCENARIO: &str = include_str!("../../../scenarios/minimal.toml");

/// Hashes at (tick, hash). Generated by running this test once with the
/// `UPDATE_HASHES=1` env var (see below); copy the printed values into here.
// Refreshed 2026-07-17: added BiomeCell.env climate field + World.biome_adaptation
// flag, then tuned the climate to low frequency (large zones for habitat selection).
// Behavior is unchanged with the flag off (env is unread; terrain/biomass generation
// is byte-identical) — only the serialized env bytes changed, so all three hashes moved.
// Refreshed 2026-07-17 (2): MAX_POPULATION raised 2_000 → 10_000 (design's 10k
// budget) and became a per-world field (`World::max_population`, scenario-
// overridable). minimal.toml pins 2000, restoring pre-raise behavior; all three
// hashes moved because the serialized World layout gained the new field.
// Refreshed 2026-07-18: added World.{world_size,biome_res,hash_res} runtime
// dimension fields (unused; behaviour identical at defaults, only serialized
// layout grew).
// Refreshed 2026-07-18: BiomeField/pheromone grid became dimension-aware
// (byte-identical at default res=128).
// Refreshed 2026-07-18: UniformSpatialHash dimension-aware (skip, no layout
// change) + PheromoneField gained world_size (serialized) — byte-identical
// at defaults.
// Refreshed 2026-07-18: added World.living_biome flag (off = byte-identical;
// only serialized layout grew).
// Refreshed 2026-07-18: added World.season_period (off = byte-identical).
// Refreshed 2026-07-18: added World.cultural_inventions flag + renamed genome
// slot 42 to Inventiveness (flag off = byte-identical; only serialized layout
// grew — the slot value semantics are unchanged).
// Refreshed 2026-07-19: the cultural-inventions ratchet is replaced by the
// full invention tree — MEME_CHANNELS widened 8→18 (inventions ride meme
// channels), BiomeCell.pollution, World.cultural_inventions renamed to
// inventions_enabled, genome slot 42 back to reserved, CodexState invention
// latches. Flag-off behavior unchanged (identity multipliers at mask 0, zero
// invention RNG draws); serialized layout changed, so all three hashes moved.
// Refreshed 2026-07-19 (2): MemeSweep no longer tracks invention channels
// (InventionAdopted reports those sweeps explicitly). Simulation physics
// unchanged; only codex bookkeeping/serialized bytes differ — tick 1000 moved
// because minimal's grazers evolve a Communicator by then.
// Refreshed 2026-07-19 (3): `inherit_meme` now skips the invention channels'
// jitter draws when `inventions_enabled` is false, restoring the pre-tree
// 8-channel RNG draw count for flag-off scenarios (the widening had silently
// drawn 10 extra jitters per Communicator birth even with the flag off). Only
// tick 1000 moved — minimal's grazers evolve a Communicator between ticks 100
// and 1000, and this undoes that trajectory perturbation for every non-
// invention culture scenario.
// Refreshed 2026-07-19: biome trade goods added AgentBuffers.inventory,
// World.{resources,resources_enabled}, CodexState.first_cross_species_trade,
// then World.terrain_habitat (geographic trade routes). All flags off =
// byte-identical trajectory; only serialized layout grew.
// Refreshed 2026-07-19 (main): cognitive layer Phases 1/3/4 — AgentBuffers
// realized-IQ fields, MEME_CHANNELS widened 18→20 (practice channels 18-19),
// CodexState practice latches. `cognition_enabled` off = behavior unchanged;
// only serialized layout grew.
// Refreshed 2026-07-19 (merge): merged the two branches (FORMAT_VERSION 8). Both
// feature sets are opt-in and off in minimal.toml, so the trajectory is
// byte-identical to either branch's — the tick-0 move is pure layout growth from
// carrying BOTH sets of new serialized fields. Regenerated post-merge.
// Refreshed 2026-07-19 (weapons): Spines/Jaws weapon module types join the
// structural-mutation pool (`Module::random_any` 9 → 11 types). New variants
// are appended at the end of the `Module` enum, so existing variant encodings
// are byte-identical; only the evolutionary trajectory drifts once a
// structural mutation draw resolves differently.
// Refreshed 2026-07-22 (E3): CodexState gains cycle/plateau/cascade detector
// scratch (FORMAT_VERSION 8→9). Pure observers — agent behavior and RNG draw
// order unchanged; the hash moves because the serialized layout grew and the
// event buffer can hold the four new event types.
// Refreshed 2026-07-23 (E4): BiomeCell.succession + World.disasters + disturbance-
// detector scratch (FORMAT_VERSION 9→10). Flag off in golden scenarios — pure
// layout growth.
// Refreshed 2026-07-23 (E5): SpeciesAgg genome moments + trait-detector scratch
// (FORMAT_VERSION 10→11) — observers only, layout growth.
// Refreshed 2026-07-23 (E6): CombatHit ambush/tool context + signature-detector
// scratch (FORMAT_VERSION 11→12) — observability only.
// Refreshed 2026-07-23 (E7): hostility records + share recipient +
// Node::SenseHostility + World.war_enabled (FORMAT_VERSION 12→13). The mutation
// pool only widens behind the flag (off everywhere here) — layout growth only,
// behavior byte-identical.
// Refreshed 2026-07-23 (E8): AgentBuffers.{anchor,harvest_exp} + World
// .{settlement_enabled,market_field} + anchor senses (FORMAT_VERSION 13→14) —
// flags off, layout growth only.
// Refreshed 2026-07-23 (E6+E7 merge): merged e7 in, which carries the e6
// still_ticks/prev_desired_direction serialization (FORMAT_VERSION 14→15).
// Layout growth only; behavior byte-identical.
// Refreshed 2026-07-23 (E9): meme-variant registry + AgentBuffers.meme_lineage
// (FORMAT_VERSION 15→16). The settled-fidelity effect is gated on settlement
// latches (off here), so behavior is byte-identical — layout growth only.
// Refreshed 2026-07-24 (E10): World.climate_drift_rate (FORMAT_VERSION 16→17).
// Drift is 0.0 in the minimal scenario, so env_optimum_at short-circuits to the
// exact undrifted value — behavior byte-identical, only the layout grew by one f32.
// Refreshed 2026-07-24 (E11): CodexState.{maladapt_streak,maladapt_active} +
// EventType::MaladaptationLag (FORMAT_VERSION 17→18). env_period == 0 in minimal,
// so the detector short-circuits and never fires — behavior byte-identical, only
// the serialized layout grew.
// Refreshed 2026-07-25 (merge of TG1 + nutrient/fertility): FORMAT_VERSION 18→19
// adds World.gene_tech_coupling (TG1) plus BiomeCell.{nutrient_quality,fertility}
// and World.{nutrient_variation,soil_fertility}. All flags are false in the minimal
// scenario, so every coupled/quality multiplier is exactly 1.0 and the discovery
// roll is unchanged — trajectory byte-identical, only the serialized layout grew.
// Refreshed 2026-07-27 (E12 sexual dimorphism): FORMAT_VERSION 19→20 adds
// AgentBuffers.sex + World.sexual_dimorphism_enabled + codex dimorphism latches
// and the two new event types. The flag is off in minimal, so sex draws are
// skipped and every dimorphism factor is exactly 1.0 — trajectory
// byte-identical, only the serialized layout grew.
const GOLDEN: &[(u64, u64)] =
    // Refreshed 2026-07-27 (climate-driven worldgen, FORMAT_VERSION 20→21):
    // gradient-noise + Whittaker generator changes every world's terrain — a
    // genuine trajectory change on top of the E12 dimorphism layout.
    &[(0, 0x347af02d7b78c855), (100, 0xf744901bb46459ad), (1000, 0xc79c46510c7c4407)];

#[test]
fn minimal_scenario_matches_golden_hashes() {
    let scenario = Scenario::parse_toml(SCENARIO).expect("parse minimal scenario");
    let mut world = scenario.instantiate();

    let mut idx = 0;
    let mut observed: Vec<(u64, u64)> = Vec::new();
    let max_tick = GOLDEN.iter().map(|(t, _)| *t).max().unwrap_or(0);

    while world.tick <= max_tick {
        while idx < GOLDEN.len() && GOLDEN[idx].0 == world.tick {
            let h = state_hash(&world);
            observed.push((world.tick, h));
            idx += 1;
        }
        if world.tick == max_tick {
            break;
        }
        step(&mut world);
    }

    if std::env::var("UPDATE_HASHES").is_ok() {
        println!("// regenerated hashes:");
        for (t, h) in &observed {
            println!("    ({}, 0x{:016x}),", t, h);
        }
        return;
    }

    for ((expected_tick, expected_hash), (got_tick, got_hash)) in GOLDEN.iter().zip(&observed) {
        assert_eq!(expected_tick, got_tick, "tick mismatch");
        assert_eq!(
            *expected_hash, *got_hash,
            "hash drift at tick {expected_tick}: expected 0x{expected_hash:016x}, got 0x{got_hash:016x}.\n\
             If this change is intentional, rerun with UPDATE_HASHES=1 and copy the printed values.",
        );
    }
}
