//! Pin deterministic state hashes at fixed ticks of the minimal scenario.
//!
//! When this test fails because hashes mismatch, the dev must either:
//! (a) confirm the change is intentional and update the constants below, or
//! (b) fix the regression. Hash changes must be deliberate.

use anabios_core::scenario::Scenario;
use anabios_core::snapshot::state_hash;
use anabios_core::tick::step;

const SCENARIO: &str = include_str!("../../../scenarios/minimal.toml");

/// Hashes at (tick, hash). Generated by running this test once with the
/// `UPDATE_HASHES=1` env var (see below); copy the printed values into here.
// Refreshed 2026-07-17: added BiomeCell.env climate field + World.biome_adaptation
// flag, then tuned the climate to low frequency (large zones for habitat selection).
// Behavior is unchanged with the flag off (env is unread; terrain/biomass generation
// is byte-identical) — only the serialized env bytes changed, so all three hashes moved.
// Refreshed 2026-07-17 (2): MAX_POPULATION raised 2_000 → 10_000 (design's 10k
// budget) and became a per-world field (`World::max_population`, scenario-
// overridable). minimal.toml pins 2000, restoring pre-raise behavior; all three
// hashes moved because the serialized World layout gained the new field.
// Refreshed 2026-07-18: added World.{world_size,biome_res,hash_res} runtime
// dimension fields (unused; behaviour identical at defaults, only serialized
// layout grew).
// Refreshed 2026-07-18: BiomeField/pheromone grid became dimension-aware
// (byte-identical at default res=128).
// Refreshed 2026-07-18: UniformSpatialHash dimension-aware (skip, no layout
// change) + PheromoneField gained world_size (serialized) — byte-identical
// at defaults.
// Refreshed 2026-07-18: added World.living_biome flag (off = byte-identical;
// only serialized layout grew).
// Refreshed 2026-07-18: added World.season_period (off = byte-identical).
// Refreshed 2026-07-18: added World.cultural_inventions flag + renamed genome
// slot 42 to Inventiveness (flag off = byte-identical; only serialized layout
// grew — the slot value semantics are unchanged).
const GOLDEN: &[(u64, u64)] =
    &[(0, 0x658c24c37e37122d), (100, 0x486eb08475de250f), (1000, 0xcc8ddc27eb59212a)];

#[test]
fn minimal_scenario_matches_golden_hashes() {
    let scenario = Scenario::parse_toml(SCENARIO).expect("parse minimal scenario");
    let mut world = scenario.instantiate();

    let mut idx = 0;
    let mut observed: Vec<(u64, u64)> = Vec::new();
    let max_tick = GOLDEN.iter().map(|(t, _)| *t).max().unwrap_or(0);

    while world.tick <= max_tick {
        while idx < GOLDEN.len() && GOLDEN[idx].0 == world.tick {
            let h = state_hash(&world);
            observed.push((world.tick, h));
            idx += 1;
        }
        if world.tick == max_tick {
            break;
        }
        step(&mut world);
    }

    if std::env::var("UPDATE_HASHES").is_ok() {
        println!("// regenerated hashes:");
        for (t, h) in &observed {
            println!("    ({}, 0x{:016x}),", t, h);
        }
        return;
    }

    for ((expected_tick, expected_hash), (got_tick, got_hash)) in GOLDEN.iter().zip(&observed) {
        assert_eq!(expected_tick, got_tick, "tick mismatch");
        assert_eq!(
            *expected_hash, *got_hash,
            "hash drift at tick {expected_tick}: expected 0x{expected_hash:016x}, got 0x{got_hash:016x}.\n\
             If this change is intentional, rerun with UPDATE_HASHES=1 and copy the printed values.",
        );
    }
}
